/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RssiMsg'
 * message type.
 */

public class RssiMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new RssiMsg of size 6. */
    public RssiMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RssiMsg of the given data_length. */
    public RssiMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg with the given data_length
     * and base offset.
     */
    public RssiMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store.
     */
    public RssiMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RssiMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RssiMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg embedded in the given message
     * at the given base offset.
     */
    public RssiMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RssiMsg embedded in the given message
     * at the given base offset and length.
     */
    public RssiMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RssiMsg> \n";
      try {
        s += "  [cmdid=0x"+Long.toHexString(get_cmdid())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [fields=";
        for (int i = 0; i < 4; i++) {
          s += "0x"+Long.toHexString(getElement_fields(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [crc=0x"+Long.toHexString(get_crc())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: cmdid
    //   Field type: short, signed
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'cmdid' is signed (true).
     */
    public static boolean isSigned_cmdid() {
        return true;
    }

    /**
     * Return whether the field 'cmdid' is an array (false).
     */
    public static boolean isArray_cmdid() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'cmdid'
     */
    public static int offset_cmdid() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'cmdid'
     */
    public static int offsetBits_cmdid() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'cmdid'
     */
    public short get_cmdid() {
        return (short)getUIntBEElement(offsetBits_cmdid(), 8);
    }

    /**
     * Set the value of the field 'cmdid'
     */
    public void set_cmdid(short value) {
        setUIntBEElement(offsetBits_cmdid(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'cmdid'
     */
    public static int size_cmdid() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'cmdid'
     */
    public static int sizeBits_cmdid() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: fields
    //   Field type: byte[], signed
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'fields' is signed (true).
     */
    public static boolean isSigned_fields() {
        return true;
    }

    /**
     * Return whether the field 'fields' is an array (true).
     */
    public static boolean isArray_fields() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'fields'
     */
    public static int offset_fields(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'fields'
     */
    public static int offsetBits_fields(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 4) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'fields' as a byte[]
     */
    public byte[] get_fields() {
        byte[] tmp = new byte[4];
        for (int index0 = 0; index0 < numElements_fields(0); index0++) {
            tmp[index0] = getElement_fields(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'fields' from the given byte[]
     */
    public void set_fields(byte[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_fields(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a byte) of the array 'fields'
     */
    public byte getElement_fields(int index1) {
        return (byte)getSIntBEElement(offsetBits_fields(index1), 8);
    }

    /**
     * Set an element of the array 'fields'
     */
    public void setElement_fields(int index1, byte value) {
        setSIntBEElement(offsetBits_fields(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'fields'
     */
    public static int totalSize_fields() {
        return (32 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'fields'
     */
    public static int totalSizeBits_fields() {
        return 32;
    }

    /**
     * Return the size, in bytes, of each element of the array 'fields'
     */
    public static int elementSize_fields() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'fields'
     */
    public static int elementSizeBits_fields() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'fields'
     */
    public static int numDimensions_fields() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'fields'
     */
    public static int numElements_fields() {
        return 4;
    }

    /**
     * Return the number of elements in the array 'fields'
     * for the given dimension.
     */
    public static int numElements_fields(int dimension) {
      int array_dims[] = { 4,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'fields' with a String
     */
    public void setString_fields(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_fields(i, (byte)s.charAt(i));
         }
         setElement_fields(i, (byte)0); //null terminate
    }

    /**
     * Read the array 'fields' as a String
     */
    public String getString_fields() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,4)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_fields(i) == (char)0) break;
             carr[i] = (char)getElement_fields(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: crc
    //   Field type: byte, signed
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'crc' is signed (true).
     */
    public static boolean isSigned_crc() {
        return true;
    }

    /**
     * Return whether the field 'crc' is an array (false).
     */
    public static boolean isArray_crc() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'crc'
     */
    public static int offset_crc() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'crc'
     */
    public static int offsetBits_crc() {
        return 40;
    }

    /**
     * Return the value (as a byte) of the field 'crc'
     */
    public byte get_crc() {
        return (byte)getSIntBEElement(offsetBits_crc(), 8);
    }

    /**
     * Set the value of the field 'crc'
     */
    public void set_crc(byte value) {
        setSIntBEElement(offsetBits_crc(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'crc'
     */
    public static int size_crc() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'crc'
     */
    public static int sizeBits_crc() {
        return 8;
    }

}
