
# /home/vsam/git/netsim/netsim_py/src/vectorl/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '5F9C93AFFE690F81154D42B909B8C781'
    
_lr_action_items = {'SEMI':([7,11,12,15,],[9,-7,13,-8,]),'IMPORT':([0,1,2,4,6,8,9,13,],[-2,-1,3,-4,-3,10,-5,-6,]),'COMMA':([11,12,15,],[-7,14,-8,]),'$end':([0,1,2,4,6,9,13,],[-2,-1,0,-4,-3,-5,-6,]),'ID':([3,5,10,14,],[7,8,11,15,]),'FROM':([0,1,2,4,6,9,13,],[-2,-1,5,-4,-3,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'newmodel':([0,],[1,]),'idlist':([10,],[12,]),'model':([0,],[2,]),'import_clause':([2,],[6,]),'from_clause':([2,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> model","S'",1,None,None,None),
  ('model -> newmodel','model',1,'p_model','parser.py',17),
  ('newmodel -> <empty>','newmodel',0,'p_newmodel','parser.py',21),
  ('model -> model import_clause','model',2,'p_model_imports','parser.py',26),
  ('model -> model from_clause','model',2,'p_model_imports','parser.py',27),
  ('import_clause -> IMPORT ID SEMI','import_clause',3,'p_import','parser.py',32),
  ('from_clause -> FROM ID IMPORT idlist SEMI','from_clause',5,'p_from_import','parser.py',37),
  ('idlist -> ID','idlist',1,'p_idlist','parser.py',41),
  ('idlist -> idlist COMMA ID','idlist',3,'p_idlist','parser.py',42),
]
